version: "3"
services:
  mysql:
    container_name: mysql
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - /data/mysql/conf:/etc/mysql/conf.d
      - /data/mysql/logs:/logs
      - /data/mysql/data:/var/lib/mysql
    command: [
          'mysqld',
          '--innodb-buffer-pool-size=80M',
          '--character-set-server=utf8mb4',
          '--collation-server=utf8mb4_unicode_ci',
          '--default-time-zone=+8:00',
          '--lower-case-table-names=1'
        ]
    environment:
      MYSQL_DATABASE: 'jira'
      MYSQL_ROOT_PASSWORD: Admin@123
  jira:
    container_name: jira
    image: "jira:pj"
    ports: 
    - "80:8080"
    volumes: 
    - /data/jira/data:/var/atlassian/jira
    environment: 
    - TZ="Asia/Shanghai"
    links:
    - mysql
    restart: alway

## 详细破解版部署参考 
# https://github.com/xiamaoxuan/Confluence-Jira/tree/master?tab=readme-ov-file
# https://www.cnblogs.com/likecoke/p/17570436.html
# java -jar atlassian-agent.jar -d -m test@test.com -n BAT -p jira -o http://192.168.100.11 -s AAAA-RNBA-VSSR-BBBB  #只需修改 -o -s 参数即可，其他可以不用动
